sudo: required
services:
  - docker

before_install:
  - docker build -t rmadan/docker-react -f Dockerfile.dev .

script:
  - docker run rmadan/docker-react npm run test -- --coverage

language:
  - generic